%-------------------------------------------------------------------%
% This is *not* the source of the vignette. It is just a place      %
% holder for R to recognize and list the vignettes of this package. %
%-------------------------------------------------------------------%

%\VignetteIndexEntry{MCLUST ver. 4 - Manual}
%\VignetteKeywords{}
%\VignettePackage{mclust}

\documentclass{article}
\begin{document}
\end{document}